package fi.koku.esb.services.customer

import fi.koku.esb.services.customer.Authorization;
import fi.koku.esb.services.customer.RuleLogger;

global java.util.List destinations;

rule "authorization-rule-demo-1"
salience 10
when
  # inspect input
  authorization: Authorization(customerPic == "111111-1111")
then
  RuleLogger.debug("a: "+authorization);
  # pass on to backend
  destinations.add("CustomerServiceBackend");
  authorization.setAllow(true);
end

rule "default rule"
salience 0
when
then
  if(destinations.isEmpty()) {
    RuleLogger.debug("default deny");
    destinations.add("DenyAccessService");
  }
end
